---
openapi: 3.0.1
info:
  title: Bedtime API V1
  version: v1
  description: API for sleep tracking with social features
  contact:
    name: API Support
    url: https://github.com/axeven/bedtime-api
paths:
  "/api/v1/users":
    post:
      summary: Create user
      tags:
      - Users
      description: Creates a new user for development/testing purposes
      parameters: []
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/User"
        '422':
          description: Validation failed
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/ValidationError"
        '400':
          description: Bad request - missing parameters
          content:
            application/json:
              schema:
                "$ref": "#/components/schemas/Error"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    name:
                      type: string
                      description: User name
                      example: John Doe
                      minLength: 1
                      maxLength: 100
                  required:
                  - name
              required:
              - user
servers:
- url: http://localhost:3000
  description: Development server
components:
  securitySchemes:
    user_id_header:
      type: apiKey
      name: X-USER-ID
      in: header
      description: User identification header
  schemas:
    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
        error_code:
          type: string
          description: Error code for programmatic handling
      required:
      - error
      - error_code
      example:
        error: Resource not found
        error_code: NOT_FOUND
    ValidationError:
      allOf:
      - "$ref": "#/components/schemas/Error"
      - type: object
        properties:
          details:
            type: object
            additionalProperties:
              type: array
              items:
                type: string
            description: Detailed validation errors by field
        example:
          error: Validation failed
          error_code: VALIDATION_ERROR
          details:
            name:
            - can't be blank
    User:
      type: object
      properties:
        id:
          type: integer
          description: User ID
          example: 1
        name:
          type: string
          description: User name
          example: John Doe
        created_at:
          type: string
          format: datetime
          description: User creation timestamp
          example: '2024-01-15T10:30:00Z'
      required:
      - id
      - name
      - created_at
